version: "3"
services:
  event_extractor:
    build: .
    ports:
      - "5280:5278"
    networks:
      - demo_network
    restart: unless-stopped
    volumes:
      - /data/coypu/static-data/static/blink/:/data/blink/models/
    container_name: event_extractor_test
    image: event_extractor_test

networks:
  demo_network:
    external: true