version: "3"
services:
  event_visualizer:
    build: .
    ports:
      - "5281:5000"
    networks:
      - demo_network
    restart: unless-stopped
    container_name: event_visualizer_container
    image: event_visualizer_image
    volumes:
      - /data/coypu/static-data/models/demo/:/data/

networks:
  demo_network:
    external: true