version: "3"
services:
  event_extractor:
    build: .
    ports:
      - "5278:5278"
    networks:
      - demo_network
    volumes:
      - /data/coypu/static-data/static/blink:/data/blink/models

networks:
  demo_network:
    external: true