event_type_detector:
  type: "custom"
  meta:
    google_drive_link: "https://drive.google.com/file/d/1AybsGHx6aSL4IP8NUWQsqMZaVvthQudd/view?usp=sharing"
    directory_to_store: "./../data/"
event_argument_extractor:
  type: "public"
  meta:
    package: "openie"
